# Write a bash script that will repeatedly prompt the user to guess a random number
# between 1 and 10, inclusively, until the user correctly guesses it. To generate a
# random number, you can use $RANDOM, which is an internal bash function that
# returns a pseudorandom integer in the range 0 – 32767. You can use the modulus
# operator to limit the range, plus an offset value so that it’s between 1 and 10,
# inclusively.
# Specifically, generate a random number between 1 and 10, inclusively. Then, in a loop,
# prompt the user to enter a number between 1 and 10. If the user’s guess is correct,
# then print a congratulatory message with the correct number generated by the
# $RANDOM function. Otherwise, if the user’s guess is not correct, print out an
# appropriate failure message and ask the user to try again. You will keep prompting
# the user and reading the user’s guess until the user guesses the number correctly.
# This bash script should be called rec04C.sh.
#
# SAMPLE OUTPUT (input in asterisks):
# $ ./rec04C.sh
# Enter a number between 1 and 10: **5**
# Sorry, you are not correct. Try again!
# Enter a number between 1 and 10: **9**
# Sorry, you are not correct. Try again!
# Enter a number between 1 and 10: **2**
# Congratulations, the number is 2.

#!/usr/bin/bash